configurationset:
  - configuration:
      name: classic_models
      Content-Type: application/json
      username: STEPZEN_CLASSIC_MODELS_USERNAME
      password: STEPZEN_CLASSIC_MODELS_PASSWORD
      ca: STEPZEN_CLASSIC_MODELS_CA

